# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

residualize <- function(X, grid_points, tree_l0, tree_r0, levels, post_states0, Is_non_terminal, children_IDs, c_learn) {
    .Call(`_boostPM_residualize`, X, grid_points, tree_l0, tree_r0, levels, post_states0, Is_non_terminal, children_IDs, c_learn)
}

G_inverse <- function(Y, tree_l, tree_r, theta_post, children_IDs) {
    .Call(`_boostPM_G_inverse`, Y, tree_l, tree_r, theta_post, children_IDs)
}

SMCforPT <- function(X, G, groups_input, grid_points, groups_pred_input, eta_R, I, model_parameters_list, M, max_K, NL, mixing_resample, thresh_resample, minimum_size, do_density_est, method) {
    .Call(`_boostPM_SMCforPT`, X, G, groups_input, grid_points, groups_pred_input, eta_R, I, model_parameters_list, M, max_K, NL, mixing_resample, thresh_resample, minimum_size, do_density_est, method)
}

