# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

do_boosting <- function(X, precision, alpha, beta, gamma, max_resol, num_each_dim, num_second, learn_rate, min_obs, nbins, eta_subsample, thresh_stop, ntrees_wait, max_n_var) {
    .Call(`_boostPM_do_boosting`, X, precision, alpha, beta, gamma, max_resol, num_each_dim, num_second, learn_rate, min_obs, nbins, eta_subsample, thresh_stop, ntrees_wait, max_n_var)
}

simulation <- function(tree_list, size_simulation, support) {
    .Call(`_boostPM_simulation`, tree_list, size_simulation, support)
}

evaluate_log_density <- function(tree_list, eval_points, support) {
    .Call(`_boostPM_evaluate_log_density`, tree_list, eval_points, support)
}

